AWSTemplateFormatVersion: 2010-09-09
Description: WAF For Akane

# Metadata:

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    AllowedValues: [dev, stg, prod]
    ConstraintDescription: must specify dev, stg or prod.
  WAFHeaderName:
    Type: String
  WAFHeaderToken:
    Type: String

Mappings: 
  AzMap: 
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1d
      3rd: ap-northeast-1c

# Conditions

# Transform

Resources:
  # WAF RuleGroupを作成
  akaneWAFRuleGroup:
    Type: AWS::WAFv2::RuleGroup
    Properties: 
      Capacity: 1500
      Description: !Sub
        - ${SystemName}-${EnvType}-waf-rule-group
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      Name: !Sub
        - ${SystemName}-${EnvType}-waf-rule-group
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      Rules:
        - Name: !Sub
            - ${SystemName}-${EnvType}-waf-rule-sqli
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
          Priority: 0
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub
              - ${SystemName}-${EnvType}-waf-rule-sqli
              - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
          Statement:
            OrStatement:
              Statements:
                - SqliMatchStatement:
                    FieldToMatch:
                      UriPath: {}
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                - SqliMatchStatement:
                    FieldToMatch:
                      QueryString: {}
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                - SqliMatchStatement:
                    FieldToMatch:
                      Body: {}
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
        - Name: !Sub
            - ${SystemName}-${EnvType}-waf-rule-xss
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub
              - ${SystemName}-${EnvType}-waf-rule-xss
              - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
          Statement:
            OrStatement:
              Statements:
                - XssMatchStatement:
                    FieldToMatch:
                      UriPath: {}
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                - XssMatchStatement:
                    FieldToMatch:
                      QueryString: {}
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                - XssMatchStatement:
                    FieldToMatch:
                      Body: {}
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
        - Name: !Sub
            - ${SystemName}-${EnvType}-waf-rule-header
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
          Priority: 2
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub
              - ${SystemName}-${EnvType}-waf-rule-header
              - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
          Statement:
            ByteMatchStatement:
              FieldToMatch:
                SingleHeader:
                  Name: !Ref WAFHeaderName
              PositionalConstraint: EXACTLY
              SearchString: !Ref WAFHeaderToken
              TextTransformations:
                - Priority: 0
                  Type: NONE        
      Scope: REGIONAL
      Tags: 
        - Key: Name
          Value: !Sub
          - ${SystemName}-${EnvType}-waf-rule-group
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
      VisibilityConfig: 
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub
          - ${SystemName}-${EnvType}-waf-rule-group
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}

  # WAF WebACLを作成
  akaneWAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Description: !Sub
        - ${SystemName}-${EnvType}-waf-web-acl
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      Name: !Sub
        - ${SystemName}-${EnvType}-waf-web-acl
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      Rules:
        - Name: !Sub
            - ${SystemName}-${EnvType}-waf-web-acl-rule
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
          OverrideAction:
            None: {}
          Statement:
            RuleGroupReferenceStatement: 
              Arn: !GetAtt akaneWAFRuleGroup.Arn
          Priority: 0
          VisibilityConfig: 
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub
              - ${SystemName}-${EnvType}-waf-web-acl-rule
              - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      Scope: REGIONAL
      Tags: 
        - Key: Name
          Value: !Sub
          - ${SystemName}-${EnvType}-waf-web-acl
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
      VisibilityConfig: 
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub
          - ${SystemName}-${EnvType}-waf-web-acl
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}

  # WAF WebACLをELBにを関連付ける
  akaneWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-elb
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      WebACLArn: !GetAtt akaneWAFWebACL.Arn         

# Outputs: